# Generated by Django 3.1.1 on 2020-09-26 08:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='none', max_length=160)),
                ('email', models.CharField(default='none', max_length=160)),
                ('phone', models.CharField(default='none', max_length=60)),
                ('message', models.CharField(default='none', max_length=1060)),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='DigitalMarketer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='none', max_length=160)),
                ('email', models.CharField(default='none', max_length=160)),
                ('phone', models.CharField(default='none', max_length=60)),
                ('about', models.TextField()),
                ('why', models.TextField()),
                ('address', models.TextField()),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='none', max_length=160)),
                ('image', models.ImageField(upload_to='images')),
                ('description', models.TextField()),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
