# Generated by Django 3.1 on 2020-09-01 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_contact'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contact',
            new_name='ContactModel',
        ),
    ]
