# Generated by Django 3.1.1 on 2020-09-27 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='facebook',
            field=models.CharField(default='none', max_length=160),
        ),
        migrations.AddField(
            model_name='team',
            name='instagram',
            field=models.CharField(default='none', max_length=160),
        ),
        migrations.AddField(
            model_name='team',
            name='twitter',
            field=models.CharField(default='none', max_length=160),
        ),
    ]
